#pragma kernel EnforceBoundaries

int gridResolution;
RWStructuredBuffer<float3> velocities;

[numthreads(8, 8, 8)]
void EnforceBoundaries(uint3 id : SV_DispatchThreadID)
{
    int index = id.x + id.y * gridResolution + id.z * gridResolution * gridResolution;

    if (id.x == 0 || id.x == gridResolution - 1 ||
        id.y == 0 || id.y == gridResolution - 1 ||
        id.z == 0 || id.z == gridResolution - 1)
    {
        velocities[index] = float3(0, 0, 0);
    }
}
